name: "Request: Bugfix"
description: "Request a fix for a bug or unexpected behavior"
title: "bug: "
assignees:
  - "tamu-haya"

body:
  - type: "textarea"
    id: "details"
    attributes:
      label: "Details"
      description: "Describe anything that was not explained in the title"
      value: "Nothing in particular."
    validations:
      required: true

  - type: "textarea"
    id: "environments"
    attributes:
      label: "Environments"
      description: "Describe the environments in which the bug occurred"
      value: "All environments."
    validations:
      required: true

  - type: "textarea"
    id: "steps-to-reproduce"
    attributes:
      label: "Steps to reproduce"
      description: "Describe the steps to reproduce the bug"
    validations:
      required: true

  - type: "textarea"
    id: "additional-comments"
    attributes:
      label: "Additional comments"
      description: "Describe anything additional you would like to share"
      value: "Nothing in particular."
    validations:
      required: true
