name: "Request: Bugfix"
description: "Request a bugfix"
title: "bug: "

body:
  - type: "markdown"
    attributes:
      value: |
        > [!IMPORTANT]
        > Before you start, check the following:
        >
        > - Do not change the prefix of the title
        >
        > - Use a sufficiently descriptive title
        >
        > - Write concisely and clearly sentences
        >
        > - Use formats such as the following where appropriate:
        >
        >   - bullet points
        >
        >   - diagrams
        >
        >   - code blocks
        >
        >   - screenshots

  - type: "textarea"
    id: "details"
    attributes:
      label: "Details"
      description: "Describe anything that was not covered in the title"
      value: "Nothing in particular."
    validations:
      required: true

  - type: "textarea"
    id: "environments"
    attributes:
      label: "Environments"
      description: "Describe the environments in which the bug occurred"
      value: "All environments."
    validations:
      required: true

  - type: "textarea"
    id: "steps-to-reproduce"
    attributes:
      label: "Steps to reproduce"
      description: "Describe the steps to reproduce the bug"
    validations:
      required: true

  - type: "textarea"
    id: "additional-information"
    attributes:
      label: "Additional information"
      description: "Describe any additional information you would like to share"
      value: "Nothing in particular."
    validations:
      required: true
