name: "Request: Feature"
description: "Request a new feature or enhancement"
title: "feat: "
assignees:
  - "tamu-haya"

body:
  - type: "textarea"
    id: "details"
    attributes:
      label: "Details"
      description: "Describe anything that was not explained in the title"
      value: "Nothing in particular."
    validations:
      required: true

  - type: "textarea"
    id: "reasons"
    attributes:
      label: "Reasons"
      description: "Describe why this feature is necessary"
    validations:
      required: true

  - type: "textarea"
    id: "concerns"
    attributes:
      label: "Concerns"
      description: "Describe any current concerns you have"
      value: "Nothing in particular."
    validations:
      required: true

  - type: "textarea"
    id: "additional-comments"
    attributes:
      label: "Additional comments"
      description: "Describe anything additional you would like to share"
      value: "Nothing in particular."
    validations:
      required: true
